services:
  backend:
    build: backend
    image: ${nexus}/app_backend:${BUILD_NUMBER}

  db:
    build: db
    image: ${nexus}/app_db:${BUILD_NUMBER}
    restart: always
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: root
      # MARIADB_ROOT_PASSWORD_FILE: ${WORKSPACE}/password.txt
      MARIADB_ROOT_PASSWORD: db-57xsl
    # secrets:
    #   - db-password
  
  frontend:
    build: frontend
    image: ${nexus}/app_frontend:${BUILD_NUMBER}
    ports:
    - 3000:3000

  test:
    build: test
    image: ${nexus}/test:${BUILD_NUMBER}
# secrets:
#    db-password:
#      file: ${WORKSPACE}/password.txt
