services:
  backend:
    build: backend
    image: app_backend

  db:
    build: db
    image: app_db
    restart: always
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: root
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password

  frontend:
    build: frontend
    image: app_frontend
    ports:
    - 3000:3000

secrets:
   db-password:
     file: db/password.txt