services:
  backend:
    build: backend
    tags: 
      - backend:1.0


  db:
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: root
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password

  frontend:
    build: frontend
    ports:
    - 3000:3000

secrets:
   db-password:
     file: db/password.txt