pipeline {
  environment {
    nexus = "10.0.0.107:8811"
  }

  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            some-label: some-label-value
        spec:
          containers:
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock    
        '''
      retries 2
    }
  }
  stages {
    stage('checkout') {
      steps {
        cleanWs()
        checkout scmGit(branches: [[name: '*/dev']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/shlomoshalit123/react-java0mysql.git']])
      } 
    }
    stage('Run docker') {
      steps {
        container('docker') {
          sh 'pwd && ls'
          sh 'docker ps'
          sh 'docker compose'
          sh 'docker compose up -d'
        }
      }
    }
  }
}